# codegen.toml

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@d6ae2dd196aae3c2486e747eb1b3cd188ea71132/core/wasmcloud-model.smithy"
[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@cb504c8b7cfcee0a8c5ecdedf75757f4718ad4e6/core/wasmcloud-model.smithy"

[[models]]
path = "."
files = [ "union-demo.smithy" ]

[rust]
output_dir = "rust"

[[rust.files]]
path = "src/union_demo.rs"
namespace = "org.wasmcloud.example.union_demo"
